// 所有站的Full name

export const stationFullName = {
    'TUM': 'Tuen Mun',
    'SIH': 'Siu Hong',
    'TIS': 'Tin Shui Wai',
    'LOP': 'Long Ping',
    'YUL': 'Yuen Long',
    'KSR': 'Kam Sheung Road',
    'TWW': 'Tsuen Wan West',
    'MEF': 'Mei Foo',
    'NAC': 'Nam Cheong',
    'AUS': 'Austin',
    'ETS': 'East Tsim Sha Tsui',
    'HUH': 'Hong Hom',
    'HOM': 'Ho Man Tin',
    'TKW': 'To Kwa Wan',
    'SUW': 'Sung Wong Toi',
    'KAT': 'Kai Tak',
    'DIH': 'Diamond Hill',
    'HIK': 'Hin Keng',
    'TAW': 'Tai Wai',
    'CKT': 'Che Kung Temple',
    'STW': 'SHa Tin Wai',
    'CIO': 'City One',
    'SHM': 'Shek Mun',
    'TSH': 'Tai Shui Hang',
    'HEO': 'Heng On',
    'MOS': 'Ma On Shan',
    'WKS': 'Wu Kai Sha',

    'POA': 'Po Lam',
    'HAH': 'Hang Hau',
    'LHP': 'Lohas Park',
	'TKO': 'Tseung Kwan O',
    'TIK': 'Tiu Keng Leng',
    'YAT': 'Yau Tong',
	'QUB': 'Quarry Bay',
    'NOP': 'North Point',

    'TUC': 'Tung Chung ',
    'SUN': 'Sunny Bay',
    'TSY': 'Tsing Yi',
	'LAK': 'Lai King',
    'NAC': 'Nam Cheong',
    'OLY': 'Olympic',
	'KOW': 'Kowloon',
    'HOK': 'Hong Kong',

    'AWE': 'AsiaWorld-Expo',
    'AIR': 'Airport',

    'LMC': 'Lok Ma Chau',
    'LOW': 'Lo Wu',
    'SHS': 'Sheung Shui',
	'FAN': 'Fanling',
    'TWO': 'Tai Wo',
    'TAP': 'Tai Po Market',
	'UNI': 'University',
    'RAC': 'Racecourse',
    'FOT': 'Fo Tan', 
	'SHT': 'Sha Tin',
    'KOT': 'Kowloon Tong',
	'MKK': 'Mong Kok East',
    'EXC': 'Exhibition Centre',
	'ADM': 'Admiralty',

    'SOH': 'South Horizons',
    'LET': 'Lei Tung',
    'WCH': 'Wong Chuk Hang',
	'OCP': 'Ocean Park',

    'TSW': 'Tsuen Wan',
    'TWH': 'Tai Wo Hau',
    'KWH': 'Kwai Hing',
	'KWF': 'Kwai Fong',
	'LCK': 'Lai Chi Kok',
    'CSW': 'Cheung Sha Wan',
    'SSP': 'Sham Shui Po',
	'PRE': 'Prince Edward',
    'MOK': 'Mong Kok',
    'YMT': 'Yau Ma Tei',
	'JOR': 'Jordan',
    'TST': 'Tsim Sha Tsui',
    'CEN': 'Central',

    'CHW': 'Chai Wan',
    'HFC': 'Heng Fa Cheun',
    'SKW': 'Shau Kei Wan',
    'SWH': 'Sai Wan Ho',
    'TAK': 'Tai Koo',
    'QUB': 'Quarry Bay',
    'NOP': 'North Point',
    'FOH': 'Fortress Hill',
    'TIH': 'Tin Hau',
    'CAB': 'Causeway Bay',
    'WAC': 'Wan Chai',
    'SHW': 'Sheung Wan',
    'SYP': 'Sai Ying Pun',
    'HKU': 'HKU',
    'KET': 'Kennedy Town',

    'TIK': 'Tiu Keng Leng',
    'LAT': 'Lam Tin',
    'KWT': 'Kwun Tong',
    'NTK': 'Ngau Tau Kok',
    'KOB': 'Kowloon Bay',
    'CHH': 'Choi Hung',
    'WTS': 'Wong Tai Sin',
    'LOF': 'Lok Fu',
    'SKM': 'Shek Kip Mei',
    'HOM': 'Ho Man Tin',
    'WHA': 'Whampoa'
}